name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Update packages
        run: |
          set -e
          sudo apt-get update
          sudo apt-get upgrade python3

      - name: Run tests
        run: python3 tests/test_application.py
