name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  test-linux:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: python3 tests/test_main.py

  test-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run tests
        run: python3 .\tests\test_main.py

